### ISSUE TITLE
Can this page control be defined in Xaml?

### ISSUE THREAD

**Issue by PJTewkesbury** [ScienceSoft-Inc/ScnSideMenu#5]
Hi,

Can this SideBarPage be defined in XAML? and if so are there any examples that use XAML in stead of pure c#?

Thanks

Peter Tewkesbury

**Comment by GaryFNQ** [comment]
Hi, 
I've been trying to get this working in an app containing a mixture of xaml and non-xaml content pages, in PCL and extracted to shared code (.shproj) files, but to no avail ... 
It this point I'm considering that the xaml compiler cannot be involved in the solution at all, but cannot burn any more time converting everything to pure code in order to quantify !

I like the simplicity, presentation and action when running the sample code, and would very much like to include the package.

... anyone experiencing any success with xaml involved?

Gary

**Comment by ScnAdmin** [comment]
Sorry, it's impossible to define the instance of this control in xaml... Maybe it will be refactored in future..
However, you may create a xaml-wrapper (a simple control\container that inherits ScnSideMenu functionality, but provides using it in xaml)
